### ISSUE TITLE
PSQLException unable to crackdown

### ISSUE THREAD

**Issue by aagarw33** [jirkapinkas/java-blog-aggregator#5]
Hi Jiri Pinkas,

First of all thank you so much for these tutorials. I am getting a PSQLException in PROD, tried to go through your github code too but does not seem to resolve. Can you please help?

I have bolded the reference that I found wrong.

root cause

Hibernate: select user0_.id as id1_0_0_, user0_.email as email2_0_0_, user0_.enabled as enabled3_0_0_, user0_.name as name4_0_0_, user0_.password as password5_0_0_ from app_user user0_ where user0_.id=?
2016-02-26T22:52:22.988346+00:00 app[web.1]: Hib
ernate: select item0_.id as id1_3_, item0_.blog_id as blog_id6_3_, item0_.description as descript2_3_, item0_.link as link3_3_, item0_.published_date as publishe4_3_, item0_.title as title5_3_ from Item item0_ left outer join Blog blog1_ on item0_.blog_id=blog1_.id where blog1_.id=? and item0_.link=?
2016-02-26T22:52:23.752140+00:00 app[web.1]: Feb 26, 2016 10:52:23 PM org.apache.coyote.AbstractProtocol start
2016-02-26T22:52:23.752148+00:00 app[web.1]: INFO: Starting ProtocolHandler ["http-nio-39649"]
2016-02-26T22:52:24.038480+00:00 app[web.1]: Hibernate: select count(item0_.id) as col_0_0_ from Item item0_
2016-02-26T22:52:24.064315+00:00 app[web.1]: Feb 26, 2016 10:52:24 PM org.apache.catalina.core.StandardWrapperValve invoke
2016-02-26T22:52:24.064329+00:00 app[web.1]:    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)
2016-02-26T22:52:24.064330+00:00 app[web.1]:    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
2016-02-26T22:52:24.064333+00:00 app[web.1]:    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273)
2016-02-26T22:52:24.064333+00:00 app[web.1]:    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
2016-02-26T22:52:24.064334+00:00 app[web.1]:    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
2016-02-26T22:52:24.064339+00:00 app[web.1]:    at org.hibernate.loader.Loader.doList(Loader.java:2610)
2016-02-26T22:52:24.064340+00:00 app[web.1]:    at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2422)
2016-02-26T22:52:24.064344+00:00 app[web.1]:    at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1339)
2016-02-26T22:52:24.064325+00:00 app[web.1]: SEVERE: Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet] with root cause
2016-02-26T22:52:24.064331+00:00 app[web.1]:    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
2016-02-26T22:52:24.064343+00:00 app[web.1]:    at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
2016-02-26T22:52:24.064347+00:00 app[web.1]:    at org.springframework.data.jpa.repository.support.SimpleJpaRepository.executeCountQuery(SimpleJpaRepository.java:623)
2016-02-26T22:52:24.064372+00:00 app[web.1]:    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
2016-02-26T22:52:24.064378+00:00 app[web.1]:    at **com.akash.blog.service.ItemService.getItems(ItemService.java:20)**
2016-02-26T22:52:24.064382+00:00 app[web.1]:    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
2016-02-26T22:52:24.064386+00:00 app[web.1]:    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
2016-02-26T22:52:24.064387+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
**2016-02-26T22:52:24.064327+00:00 app[web.1]: org.postgresql.util.PSQLException: ERROR: relation "item" does not exist**
2016-02-26T22:52:24.064332+00:00 app[web.1]:    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
2016-02-26T22:52:24.064340+00:00 app[web.1]:    at org.hibernate.loader.Loader.doList(Loader.java:2593)
2016-02-26T22:52:24.064356+00:00 app[web.1]:    at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java:371)
2016-02-26T22:52:24.064362+00:00 app[web.1]:    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:468)
2016-02-26T22:52:24.064368+00:00 app[web.1]:    at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
2016-02-26T22:52:24.064376+00:00 app[web.1]:    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
2016-02-26T22:52:24.064380+00:00 app[web.1]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Thanks,
Akash

**Comment by aagarw33** [comment]
Hey Jiri, resolved something was screwed up in my entities. Thanks again for the informative tutorial, I hope you make another series with the updated version of JBA. 

Regards,
Akash
